format_version: 10
pipelines:
  frontend-deployment:
    group: deployment-group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 2
    materials:
      git-frontend:
        git: https://github.com/jk0789/gocd_code.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Deploy-Frontend:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            run-commands:
              timeout: 0
              variables:
                BUILD_DIR: /home/joshi/builds
                UI_TARGET_DIR: /var/www/html
                UI_ARCHIVE_DIR: /home/joshi/ui-archive
                UI_TEMP_DIR: ${UI_ARCHIVE_DIR}/temp-extract
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        echo "Exporting environment variables..."
                        export BUILD_DIR=/home/joshi/builds
                        export UI_TARGET_DIR=/var/www/html
                        export UI_ARCHIVE_DIR=/home/joshi/ui-archive
                        export UI_TEMP_DIR=${UI_ARCHIVE_DIR}/temp-extract
                        export SERVICE=PrimeSquare.service
                        echo "Processing frontend (ps_ui)..."
                        UI_ZIP=$(ls ${BUILD_DIR}/ps_ui*.zip 2>/dev/null | head -n 1)
 
                        if [ -z "${UI_ZIP}" ]; then
                          echo "No ps_ui zip file found in ${BUILD_DIR}!"
                          exit 1
                        fi
 
                        echo "Found frontend zip: ${UI_ZIP}"
 
                        sudo mkdir -p "${UI_TEMP_DIR}" "${UI_ARCHIVE_DIR}" || { echo "Failed to create UI directories"; exit 1; }
                        sudo unzip -o "${UI_ZIP}" -d "${UI_TEMP_DIR}" || { echo "Failed to unzip ps_ui"; exit 1; }
 
                        echo "Granting temporary permissions to ${UI_TARGET_DIR}..."
                        sudo chmod -R 777 "${UI_TARGET_DIR}" || { echo "Failed to grant permissions"; exit 1; }
 
                        echo "Replacing files in ${UI_TARGET_DIR}..."
                        sudo mkdir -p "${UI_TARGET_DIR}" || { echo "Failed to create ${UI_TARGET_DIR}"; exit 1; }
                        sudo rm -rf "${UI_TARGET_DIR}"/* || { echo "Failed to clean ${UI_TARGET_DIR}"; exit 1; }
                        sudo cp -r "${UI_TEMP_DIR}"/* "${UI_TARGET_DIR}" || { echo "Failed to copy UI files"; exit 1; }
 
                        echo "Reverting permissions of ${UI_TARGET_DIR}..."
                        sudo chmod -R 755 "${UI_TARGET_DIR}" || { echo "Failed to revert permissions"; exit 1; }
 
                        rm -rf "${UI_TEMP_DIR}" || { echo "Failed to clean up UI temp dir"; exit 1; }

                        
                        if [ ! -f /etc/apache2/sites-available/primesquare.conf ]; then
                          echo "File /etc/apache2/sites-available/primesquare.conf not found. Checking for replacement..."
                          
                                                  
                          if [ -f /etc/apache2/sites-available/primesquare.conf ]; then
                            echo "Replacing primesquare.conf..."
                            sudo cp /var/go/pipelines/frontend-deployment/primesquare.conf /etc/apache2/sites-available/
                            echo "primesquare.conf replaced successfully."
                          else
                            echo "primesquare.conf not found in the repo. Skipping replacement."
                          fi
                        else-
                          echo "primesquare.conf already exists. Skipping replacement."
                        fi

                        -- Set the base UI URL from application.properties
                        baseUiUrl=$(cat /home/joshi/prime-square/application.properties | grep "base.ui.url" -i | grep -o 'ps-[^ ]*..net')

                        if [ -z "$baseUiUrl" ]; then
                          echo "base.ui.url not found in application.properties!"
                          exit 1
                        fi

                        echo "Replacing URLs in frontend files..."
                        sudo sed -i "s/ps-targethost:3804/\$baseUiUrl/g" /var/www/html/prime-square/main*.js || { echo "Failed to update main*.js"; exit 1; }
                        sudo sed -i "s/ps-targethost:3804/\$baseUiUrl/g" /var/www/html/prime-square/assets/environment/environment.json || { echo "Failed to update environment.json"; exit 1; }
                        sudo sed -i "s/ps-targethost:3804/\$baseUiUrl/g" /var/www/html/prime-square/403error.html || { echo "Failed to update 403error.html"; exit 1; }
 
                        echo "Restarting Apache2..."
                        sudo systemctl restart apache2 || { echo "Failed to restart Apache2"; exit 1; }
 
                        echo "frontend deployment complete."
              resources:
                - joshi
              environment_variables:
                GOCD_ENVIRONMENT: Frontandbackend
environments:
  Frontandbackend:
    pipelines:
      - frontend-deployment
