format_version: 10
pipelines:
  jktest04:
    group: deployment-group
    label_template: "${COUNT}"
    lock_behavior: none
    display_order: 1
    materials:
      git-backend:
        git: https://github.com/jk0789/gocd_code.git
        shallow_clone: false
        auto_update: true
        branch: final
    stages:
      - name: Deploy-Backend
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
        jobs:
          - name: run-commands
            timeout: 0
            environment_variables:
              BUILD_DIR: /home/joshi/builds
              BE_TARGET_DIR: /home/joshi/prime-square
              BE_ARCHIVE_DIR: /home/joshi/archive
              SERVICE: PrimeSquare.service
              DB_SCRIPTS_DIR: /home/joshi/prime-square/database-scripts
              DB_USER: psdbadmin
              DB_PASS: 6%EOm@Te1sb19Th6
              SFTP_HOST: 172.16.7.116
              SFTP_USER: surya
              SFTP_KEY: /var/go/.ssh/id_rsa
              SFTP_UPLOADS_DIR: uploads
            tasks:
              - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - |
                      echo "Accessing SFTP machine to fetch the backend zip file..."
                      mkdir -p "${BUILD_DIR}"
                      sftp -o StrictHostKeyChecking=no -i "${SFTP_KEY}" ${SFTP_USER}@${SFTP_HOST} <<EOF
                      cd ${SFTP_UPLOADS_DIR}
                      get ps_be*.zip ${BUILD_DIR}/ps_be_backend.zip
                      bye
                      EOF
                      unzip -o "${BUILD_DIR}/ps_be_backend.zip" -d "${BUILD_DIR}"
                      mkdir -p "${BE_TARGET_DIR}"
                      unzip -o "${BUILD_DIR}/ps_be_backend.zip" -d "${BE_TARGET_DIR}"
                      sudo chown -R joshi:joshi "${BE_TARGET_DIR}"
                      sudo cp "${BE_TARGET_DIR}/service/PrimeSquare.service" /etc/systemd/system/
                      sudo chmod +x "${BE_TARGET_DIR}/wrapper.sh"
                      sudo systemctl daemon-reload
                      sudo chmod -R +x "${DB_SCRIPTS_DIR}"
                      mysql < "${DB_SCRIPTS_DIR}/ddl_drop_schema_script.sql" -u ${DB_USER} -p${DB_PASS}
                      mysql < "${DB_SCRIPTS_DIR}/idfc_primesquare_workflow_ddl_dml.sql" -u ${DB_USER} -p${DB_PASS}
                      mysql < "${DB_SCRIPTS_DIR}/ddl_create_scripts.sql" -u ${DB_USER} -p${DB_PASS}
                      mysql < "${DB_SCRIPTS_DIR}/dml_insert_scripts.sql" -u ${DB_USER} -p${DB_PASS}
                      mysql < "${DB_SCRIPTS_DIR}/ps_index_create.sql" -u ${DB_USER} -p${DB_PASS}
                      sudo systemctl enable ${SERVICE}
                      sudo systemctl start ${SERVICE}
                      sudo systemctl status ${SERVICE}
            resources:
              - joshi

environments:
  jktest04:
    pipelines:
      - jktest04
