format_version: 10
pipelines:
  jktest04:
    group: deployment-group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 1
    materials:
      git-backend:
        git: https://github.com/jk0789/gocd_code.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Manual-Approval:
          fetch_materials: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            - name: decide-deployment
              tasks:
                - exec:
                    command: echo
                    arguments:
                      - "Manual approval required. Proceeding to deployment stages."

      - Preparation:
          fetch_materials: true
          clean_workspace: false
          jobs:
            - name: prepare-environment
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        echo "Preparing environment..."

                        if [ -d "/home/joshi/prime-square" ]; then
                          echo "Found existing 'prime-square' directory. Proceeding with regular deployment..."

                          echo "Stopping PrimeSquare.service..."
                          sudo systemctl stop PrimeSquare.service || { echo "Failed to stop service"; exit 1; }

                          echo "Archiving existing core JAR..."
                          sudo mv /home/joshi/prime-square/core-*.jar /home/joshi/archive/core-$(date +%F-%T).jar || { echo "Failed to archive core JAR"; exit 1; }

                          echo "Replacing core JAR..."
                          sudo mv /home/joshi/archive/temp-extract/core-*.jar /home/joshi/prime-square/ || { echo "Failed to replace core JAR"; exit 1; }

                          echo "Preparing for Database Update..."
                          echo "REGULAR_DEPLOYMENT" > /home/joshi/deployment_type
                        else
                          echo "No 'prime-square' directory found. Proceeding with fresh deployment..."
                          echo "FRESH_DEPLOYMENT" > /home/joshi/deployment_type
                          exit 2  
                        fi

      - Database-Update-Approval:
          fetch_materials: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            - name: approve-database-update
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        DEPLOYMENT_TYPE=$(cat /home/joshi/deployment_type)
                        if [ "$DEPLOYMENT_TYPE" == "REGULAR_DEPLOYMENT" ]; then
                          echo "Manual approval required for database update in regular deployment."
                          exit 1
                        else
                          echo "Skipping manual approval for fresh deployment."
                          exit 0
                        fi

      - Database-Update:
          fetch_materials: false
          clean_workspace: false
          jobs:
            - name: update-database
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        DEPLOYMENT_TYPE=$(cat /home/joshi/deployment_type)

                        if [ "$DEPLOYMENT_TYPE" == "REGULAR_DEPLOYMENT" ]; then
                          echo "Executing database scripts for regular deployment..."
                          mysql < /home/joshi/prime-square/database-scripts/ddl_drop_schema_script.sql -u psdbadmin -p6%EOm@Te1sb19Th6 -h 172.16.7.115 || { echo "Failed to drop schema"; exit 1; }
                          mysql < /home/joshi/prime-square/database-scripts/ddl_create_scripts.sql -u psdbadmin -p6%EOm@Te1sb19Th6 -h 172.16.7.115 || { echo "Failed to create schema"; exit 1; }
                          mysql < /home/joshi/prime-square/database-scripts/dml_insert_scripts.sql -u psdbadmin -p6%EOm@Te1sb19Th6 -h 172.16.7.115 || { echo "Failed to insert data"; exit 1; }
                          echo "Database update complete."
                        else
                          echo "Skipping database update for fresh deployment."
                        fi

      - New-Deployment:
          fetch_materials: false
          clean_workspace: false
          jobs:
            - name: fresh-deployment
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        DEPLOYMENT_TYPE=$(cat /home/joshi/deployment_type)

                        if [ "$DEPLOYMENT_TYPE" == "FRESH_DEPLOYMENT" ]; then
                          echo "Fresh deployment detected. Setting up environment..."

                          echo "Creating 'prime-square' directory..."
                          sudo mkdir -p /home/joshi/prime-square || { echo "Failed to create target directory"; exit 1; }

                          echo "Unzipping all contents to 'prime-square'..."
                          sudo unzip -o /home/joshi/archive/temp-extract/*.zip -d /home/joshi/prime-square || { echo "Failed to unzip contents"; exit 1; }

                          echo "Copying service file to /etc/systemd/system/..."
                          sudo cp /home/joshi/prime-square/service/PrimeSquare.service /etc/systemd/system/ || { echo "Failed to copy service file"; exit 1; }

                          echo "Reloading systemd daemon..."
                          sudo systemctl daemon-reload || { echo "Failed to reload daemon"; exit 1; }

                          echo "Starting PrimeSquare.service..."
                          sudo systemctl start PrimeSquare.service || { echo "Failed to start service"; exit 1; }

                          echo "Fresh deployment complete."

                          echo "Executing database scripts for fresh deployment..."
                          mysql < /home/joshi/prime-square/database-scripts/ddl_drop_schema_script.sql -u psdbadmin -p6%EOm@Te1sb19Th6 -h 172.16.7.115 || { echo "Failed to drop schema"; exit 1; }
                          mysql < /home/joshi/prime-square/database-scripts/ddl_create_scripts.sql -u psdbadmin -p6%EOm@Te1sb19Th6 -h 172.16.7.115 || { echo "Failed to create schema"; exit 1; }
                          mysql < /home/joshi/prime-square/database-scripts/dml_insert_scripts.sql -u psdbadmin -p6%EOm@Te1sb19Th6 -h 172.16.7.115 || { echo "Failed to insert data"; exit 1; }
                          echo "Database update for fresh deployment complete."
                        else
                          echo "Skipping new deployment stage."
                        fi

      - Service-Configuration:
          fetch_materials: false
          clean_workspace: false
          jobs:
            - name: configure-and-start-service
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        echo "Configuring and restarting service..."

                        echo "Reloading systemd daemon..."
                        sudo systemctl daemon-reload || { echo "Failed to reload daemon"; exit 1; }

                        echo "Starting PrimeSquare.service..."
                        sudo systemctl start PrimeSquare.service || { echo "Failed to start service"; exit 1; }

                        echo "Service started successfully."
              resources:
                - joshi                   
environments:
  jktest04:
    pipelines:
      - jktest04                        
