---
format_version: 10
pipelines:
  jktest04:
    group: deployment-group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 1
    materials:
      git-backend:
        git: https://github.com/jk0789/gocd_code.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Deploy-Backend:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            run-commands:
              timeout: 0
              variables:
                BUILD_DIR: /home/joshi/builds
                BE_TARGET_DIR: /home/joshi/prime
                BE_ARCHIVE_DIR: /home/joshi/archive
                BE_TEMP_DIR: ${BE_ARCHIVE_DIR}/temp-extract
                SERVICE: PrimeSquare.service
                DB_SCRIPTS_DIR: /home/joshi/prime-square/database-scripts
                DB_USER: psdbadmin
                DB_PASS: 6%EOm@Te1sb19Th6
                SFTP_HOST: 172.16.7.110
                SFTP_USER: sftp_gocd
                SFTP_UPLOADS_DIR: uploads
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        echo "Exporting environment variables..."

                        export BUILD_DIR=/home/joshi/builds

                        export BE_TARGET_DIR=/home/joshi/prime

                        export UI_TARGET_DIR=/var/www/html

                        export BE_ARCHIVE_DIR=/home/joshi/archive

                        export UI_ARCHIVE_DIR=/home/joshi/ui-archive

                        export BE_TEMP_DIR=${BE_ARCHIVE_DIR}/temp-extract

                        export UI_TEMP_DIR=${UI_ARCHIVE_DIR}/temp-extract

                        export SERVICE=PrimeSquare.service

                        export DB_SCRIPTS_DIR=/home/joshi/prime-square/database-scripts
                        export DB_USER=psdbadmin
                        export DB_PASS=6%EOm@Te1sb19Th6
                        export SFTP_HOST=172.16.7.110
                        export SFTP_USER=sftp_gocd
                        export SFTP_KEY=/var/go/.ssh/id_rsa
                        export SFTP_UPLOADS_DIR=uploads

                        echo "Creating build directory..."
                        mkdir -p "${BUILD_DIR}" || { echo "Failed to create ${BUILD_DIR}"; exit 1; }
                        
                        echo "Checking build directory contents..."

                        ls -lh ${BUILD_DIR}

                        echo "Processing backend (ps_be)..."

                        BE_ZIP=$(ls ${BUILD_DIR}/ps_be*.zip 2>/dev/null | head -n 1)


                        if [ -z "${BE_ZIP}" ]; then
                          echo "No ps_be zip file found in ${BUILD_DIR}!"
                          exit 1
                        fi


                        echo "Found backend zip: ${BE_ZIP}"


                        sudo mkdir -p "${BE_TEMP_DIR}" "${BE_ARCHIVE_DIR}" || { echo "Failed to create backend directories"; exit 1; }

                        sudo unzip -o "${BE_ZIP}" -d "${BE_TEMP_DIR}" || { echo "Failed to unzip ps_be"; exit 1; }


                        JAR_FILE=$(find "${BE_TEMP_DIR}" -type f -name "core-*.jar" | head -n 1)


                        if [ -z "${JAR_FILE}" ]; then
                          echo "No core-*.jar file found in the ps_be zip!"
                          exit 1
                        fi


                        echo "Replacing jar in ${BE_TARGET_DIR}..."

                        sudo mkdir -p "${BE_TARGET_DIR}" || { echo "Failed to create ${BE_TARGET_DIR}"; exit 1; }

                        sudo cp "${JAR_FILE}" "${BE_TARGET_DIR}" || { echo "Failed to copy JAR file"; exit 1; }

                        sudo rm -rf "${BE_TEMP_DIR}" || { echo "Failed to clean up BE temp dir"; exit 1; }


                        echo "Restarting backend service..."

                        sudo systemctl restart ${SERVICE} || { echo "Failed to restart ${SERVICE}"; exit 1; }


                        echo "Backend deployment complete."
              resources:
                - joshi
               
environments:
  jktest04:
    pipelines:
      - jktest04
