pipelines:
  PrimeSquare-pipeline:
    group: PrimeSquare-group
    label_template: "${COUNT}"
    materials:
      git:
        url: https://github.com/jk0789/gocd_code.git
        branch: main
        destination: app-repo
    stages:
      - name: deploy
        jobs:
          - name: extract-and-replace
            tasks:
              - exec:
                  command: bash
                  arguments:
                    - -c
                    - |
                      # Set variables
                      WORKDIR="/home/ubuntu/prime-square"
                      SERVICE="PrimeSquare.service"

                      # Stop the service
                      echo "Stopping service $SERVICE..."
                      sudo systemctl stop $SERVICE

                      # Extract the build name and find the JAR file
                      BUILD_NAME=$(basename $(pwd))
                      echo "Build name extracted: $BUILD_NAME"

                      JAR_FILE=$(find app-repo -type f -name "core-*.jar" | head -n 1)
                      if [ -z "$JAR_FILE" ]; then
                        echo "No JAR file matching 'core-*.jar' found!"
                        exit 1
                      fi
                      echo "Found JAR file: $JAR_FILE"

                      # Move the new JAR to the workdir
                      TARGET_JAR="$WORKDIR/$(basename $JAR_FILE)"
                      if [ -f "$TARGET_JAR" ]; then
                        echo "Removing existing JAR in $WORKDIR..."
                        rm -f "$TARGET_JAR"
                      fi
                      echo "Copying new JAR to $WORKDIR..."
                      cp "$JAR_FILE" "$TARGET_JAR"

                      # Restart the service
                      echo "Starting service $SERVICE..."
                      sudo systemctl start $SERVICE
